services:
  nginx:
    image: 'yukozoom/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  server:
    image: 'yukozoom/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
  client:
    image: 'yukozoom/multi-client'
    mem_limit: 128m
    hostname: client
  worker:
    image: 'yukozoom/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
