name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t yukozoom/multi-client:latest ./client
      - run: docker build -t yukozoom/multi-nginx:latest ./nginx
      - run: docker build -t yukozoom/multi-server:latest ./server
      - run: docker build -t yukozoom/multi-worker:latest ./worker

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yukozoom/multi-client:latest
      - run: docker push yukozoom/multi-nginx:latest
      - run: docker push yukozoom/multi-server:latest
      - run: docker push yukozoom/multi-worker:latest

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Multi-docker-udemy
          environment_name: Multi-docker-udemy-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-047719653264
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
